version: 1.0.{build}
clone_depth: 50  # The same depth Travis has
image: Visual Studio 2019

environment:
  matrix:
    # Python36
    - PYTHON: "C:\\Python36"
    # Python37
    - PYTHON: "C:\\Python37"
    # Python38
    - PYTHON: "C:\\Python38"
    # Python36-x64
    - PYTHON: "C:\\Python36-x64"
    # Python37-x64
    - PYTHON: "C:\\Python37-x64"
    # Python38-x64
    - PYTHON: "C:\\Python38-x64"

install:
  # We need wheel installed to build wheels
  - "%PYTHON%\\python.exe -m pip install pip --upgrade"
  - "%PYTHON%\\python.exe -m pip install wheel setuptools Cython pytest -r requirements.txt"

test_script:
  - "%PYTHON%\\python.exe setup.py develop"
  - "%PYTHON%\\python.exe -m pytest -v -l ms_peak_picker/test/ --junitxml=junit/test-results.xml"

build_script:
  - ".ci\\build.cmd %PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: dist\*.whl
    name: wheels
